import { Brygada_1918, Great_Vibes } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/nav";
import Footer from "@/components/footer/footer";
import { TooltipProvider } from "@/components/ui/tooltip";
import { GoogleTagManager } from '@next/third-parties/google'; 

const geistPrimary = Brygada_1918({
  variable: "--font-brygada-1918",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const geistSecondary = Great_Vibes({
  variable: "--font-great-vibes",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistPrimary.variable} ${geistSecondary.variable} antialiased`}
      >
        <GoogleTagManager gtmId="GTM-TZ44KH95" />
        <TooltipProvider>
          <div>
            <Navbar />
            {children}
            <Footer />
          </div>
        </TooltipProvider>
      </body>
    </html>
  );
}
